<?php
/**
 * Created by PhpStorm.
 * User: Hpp
 * Date: 06.07.2018
 * Time: 0:06
 */

namespace common\models;


use yii\behaviors\SluggableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class ActiveRecord extends \yii\db\ActiveRecord
{
//    public function behaviors()
//    {
//        parent::behaviors(); // TODO: Change the autogenerated stub
//        return
//            [
//                ['class' => TimestampBehavior::className(),
//                    'attributes' => [
//                        self::EVENT_BEFORE_INSERT => ['created_at'],
//                    ],
//                    'value' => new Expression('NOW()'),
//                ],
//                [
//                    'class' => SluggableBehavior::className(),
//                    'attribute' => 'header',
//                    'ensureUnique' => true,
//                ],
//
//            ];
//
//    }

    public function createImg($model, $img, $unique)
    {
        $file = $this->file;
        $fileName = $file->getBaseName() . "{$this->header}" . "." . $file->getExtension();
        $filePath = \Yii::getAlias("@webroot/img/$fileName");
        $this->preview = $filePath;
        $this->save();
        $this->file->saveAs($filePath);
        Image::thumbnail("@webroot/img/$fileName", 200, 200)->save(\Yii::getAlias("@webroot/img/small/$fileName",['quality' => 70]));
    }

}